const BUCKET_NAME = 'hiphopvolumebucket'
const IAM_USER_KEY = 'AKIAXDGILESFEP4MB55R'
const IAM_USER_SECRET = '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'
exports.BUCKET_NAME = BUCKET_NAME;
exports.IAM_USER_KEY = IAM_USER_KEY;
exports.IAM_USER_SECRET = IAM_USER_SECRET;